import { Project, Validaciones } from "../types";
import { getRequiredDocuments } from "./documentRules";

export const runQualityGates = (project: Project): Validaciones => {
    const v: Validaciones = {
        errores: [],
        advertencias: [],
        faltantes: [],
        sugerencias_mejora: []
    };

    // --- GATE A: CLASIFICACIÓN ---
    // Enforced by UI generally, but check consistency
    if (!project.clasificacion.tipo_proyecto) {
        v.errores.push("Gate A: Falta definir el Tipo de Proyecto.");
    }
    if (!project.clasificacion.tipo_beneficiario) {
        v.errores.push("Gate A: Falta definir el Tipo de Beneficiario.");
    }

    // --- GATE B: RESTRICCIONES DE CAMPO ---
    if (project.paso2_datos_proyecto.titulo.texto.length > 150) {
        v.errores.push(`Gate B: El título excede 150 caracteres (${project.paso2_datos_proyecto.titulo.texto.length}).`);
    }
    if (!project.paso2_datos_proyecto.titulo.texto.trim()) {
        v.faltantes.push("Falta ingresar el Título del proyecto.");
    }

    if (project.paso2_datos_proyecto.resumen.texto.length > 400) {
        v.errores.push(`Gate B: El resumen excede 400 caracteres (${project.paso2_datos_proyecto.resumen.texto.length}).`);
    }
    if (!project.paso2_datos_proyecto.resumen.texto.trim()) {
        v.faltantes.push("Falta ingresar el Resumen Ejecutivo.");
    }

    // --- GATE C: COHERENCIA INTERNA ---
    // 1. Duración vs Actividades
    const durationMonths = project.paso2_datos_proyecto.duracion.meses;
    const activities = project.paso3_cronograma.actividades;

    if (durationMonths <= 0) {
        v.errores.push("Gate C: La duración del proyecto debe ser mayor a 0 meses.");
    }

    const exceedingActivity = activities.find(a => (a.mes_inicio_relativo + (a.unidad === 'meses' ? a.duracion : a.duracion / 30)) > durationMonths + 1); // +1 buffer
    if (exceedingActivity) {
        v.errores.push(`Gate C: La actividad "${exceedingActivity.nombre}" excede la duración total del proyecto.`);
    }

    // 2. Objetivos vs Actividades
    // Check if there are objectives without linked activities (Logic: MVP assumes linkage text exists or checked manually)
    // For specific objectives list:
    const objectives = project.paso2_datos_proyecto.objetivos.objetivos_especificos;
    if (objectives.length === 0) {
        v.faltantes.push("Faltan Objetivos Específicos.");
    }

    if (activities.length === 0) {
        v.faltantes.push("Falta desarrollar el Cronograma de Actividades.");
    }

    // 3. Actividades vs Presupuesto
    const budgetItems = project.paso4_presupuesto.items;
    if (activities.length > 0 && budgetItems.length === 0) {
        v.advertencias.push("Gate C: Tienes actividades definidas pero el presupuesto está vacío.");
    }

    // --- GATE D: RETRIBUCIÓN CULTURAL ---
    // Debe ser medible + medio probatorio
    // MVP logic: Check if retribucion actions exist and have metrics/evidence
    // NOTE: Current schema puts text in "retribucion_cultural.acciones[]" ? No, schema says AccionRetribucion object.
    // Let's assume user fills text in description or uses the array. 
    // The previous prompt text implied structuring it. Let's check the array if used, or description text.

    // Check description first
    if (!project.paso2_datos_proyecto.retribucion_cultural.descripcion && project.paso2_datos_proyecto.retribucion_cultural.acciones.length === 0) {
        v.errores.push("Gate D: Falta definir la Retribución Cultural.");
    } else {
        // If using actions array, check completeness
        project.paso2_datos_proyecto.retribucion_cultural.acciones.forEach((acc, idx) => {
            if (acc.medible_por.length === 0) {
                v.advertencias.push(`Gate D: La acción de retribución #${idx + 1} no indica cómo será medida.`);
            }
            if (acc.medio_probatorio.length === 0) {
                v.errores.push(`Gate D: La acción de retribución #${idx + 1} no tiene medio probatorio.`);
            }
        });
    }

    // --- GATE E: DOCUMENTOS ---
    // Admisibilidad
    const reqDocs = getRequiredDocuments(project);
    // In MVP we don't track "uploaded file" state in the Project object yet per previous steps, 
    // but we can check if the list matches assumptions or if PI is declared.

    // Check Declara Uso of PI
    if (project.paso5_documentos.propiedad_intelectual.declara_uso) {
        // Check if authorization doc is present (implicitly generated by rule engine, but double check logic)
        const hasAuthDoc = reqDocs.some(d => d.name.includes("Autorización") || d.name.includes("Licencia"));
        if (!hasAuthDoc) {
            v.errores.push("Gate E: Se declara uso de propiedad intelectual pero falta exigir el documento de autorización.");
        }
    }

    return v;
};
